### CONSTANTS
from json import JSONDecoder

# BACKGOUND
GAME_WIDTH = 360
GAME_HEIGHT = 640

# FROG
FROG_START_X = GAME_WIDTH / 8
FROG_START_Y = GAME_HEIGHT / 2
FROG_WIDTH = 55
FROG_HEIGHT = 64

# BLOCK
BLOCK_WIDTH = 183
BLOCK_HEIGHT = 72

#BUTTON
SETTINGS_BUTTON_WIDTH = 47
SETTINGS_BUTTON_HEIGHT = 47

BUTTON_WIDTH = 59
BUTTON_HEIGHT = 33

CIRCLE_WIDTH = 25
CIRCLE_HEIGHT = 25

SOUND_SETTINGS = {
        "background": True,
        "game": True
    }

# TEXT
TEXT_FONT_SIZE = 30

# HIGHSCORE
#HIGHSCORE_FILE = "highscore.txt

# PIPE
PIPE_WIDTH = 50
PIPE_HEIGHT = 400
PIPE_OPENING_SPACE = GAME_HEIGHT / 4
PIPE_SPEED = -2

# Cloud (background decoration)
CLOUD_WIDTH = 209
CLOUD_HEIGHT = 120
CLOUD_SPEED = -2

# Game mechanics
GRAVITY = 0.4
JUMP_STRENGTH = -6
